### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by bittlingmayer** [yusufsyaifudin/node-fasttext#2]
npm-debug.log attached.

[npm-debug.log.txt](https://github.com/yusufsyaifudin/node-fasttext/files/1172895/npm-debug.log.txt)

**Comment by yusufsyaifudin** [comment]
Hi @bittlingmayer!

I suspect that you are using non-supported NodeJS version for this library, as I was mentioned in [.travis.yml](https://github.com/yusufsyaifudin/node-fasttext/blob/master/.travis.yml#L4) file, the minimum required version for this library is 6.9.

I recently trying to reproduce your issue using NodeJS 6.2.2 and NPM 3.9.5 and got a resemble npm-debug.log.txt errors like yours. So, by this, I convinced that it was only because of your NodeJS version. Also please note that I was reproduce using GCC version 5.4.0, but in Travis, it just run using [GCC version 4.6.3](https://travis-ci.org/yusufsyaifudin/node-fasttext#L25)

Should you try with the latest version of NodeJS (maybe 8 since it will become LTS version by this October if it meets the release timeline) and please close this issue if it is resolved. Thanks!

**Comment by bittlingmayer** [comment]
@yusufsyaifudin Sounds likely, will try now

**Comment by bittlingmayer** [comment]
Yes, that fixed it.

Now I see a new issue, #3.
